### ISSUE TITLE
Rename to StreetNameWasNamed

### ISSUE THREAD

**Issue by ArneD** [Informatievlaanderen/streetname-registry#5]
https://github.com/Informatievlaanderen/streetname-registry/blob/8c7e27c9acead19563c8a66c0e29ea3238897ae6/src/StreetNameRegistry/StreetName/Events/StreetNameNameWasNamed.cs#L8

Should we rename this to StreetNameWasNamed?

**Comment by CumpsD** [comment]
Sounds good to me
